name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/im2deep
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build
        run: python -m build

      - name: Install
        run: pip install dist/im2deep-*.whl

      - name: Test package
        run: |
          im2deep --help

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
